#!/bin/bash

# -------------------------------------------------------------------------- #
# Given the root directory of a SW tree, this script traverse it and check   #
# the test status of every build directory from file test.log.               #
# Author: Reuben Budiardja (reubendb@utk.edu, NICS, June 20015               #
# -------------------------------------------------------------------------- # 

SWROOT=$1

#-- Define colors for shell
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CLEAR='\033[0m' # No Color
#-

cd $SWROOT

for PACKAGE in `ls | grep -v modulefiles | grep -v visit`; 
do
  
  cd $PACKAGE
  
  for VERSION in `ls | grep -v description | grep -v support | grep -v versions`;
  do

    cd $VERSION
    
    for BUILD in `ls`;
    do
      
      cd $BUILD
      
      if [ ! -e status ]; then
        echo -e $PACKAGE $VERSION $BUILD ${RED}:UNKNOWN:${CLEAR} \
             | awk '{ printf "%-15s %-15s %-25s %-7s \n", $1, $2, $3, $4}'  
        cd ..
        continue
      fi
      
      tail -n 1 status | grep -q "unverified" 
      if [ $? -eq 0 ]; then
        echo -e $PACKAGE $VERSION $BUILD ${YELLOW}:UNVERIFIED:${CLEAR} \
        | awk '{ printf "%-15s %-15s %-25s %-7s \n", $1, $2, $3, $4}'
        cd ..
        continue
      fi
      
      tail -n 1 status | grep -q "verified" 
      if [ $? -eq 0 ]; then
        echo -e $PACKAGE $VERSION $BUILD ${GREEN}:VERIFIED:${CLEAR} \
        | awk '{ printf "%-15s %-15s %-25s %-7s \n", $1, $2, $3, $4}'
      fi
      
      if [ -e .lock ]; then
        echo -e $PACKAGE $VERSION $BUILD ${YELLOW}:PGRS:${CLEAR} \
             | awk '{ printf "%-15s %-15s %-25s %-7s \n", $1, $2, $3, $4}'  
      fi
      
      cd ..
    
    done
    
    cd ..
  
  done
  
  cd ..
  
done
